name: Update README cards

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate stats card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: stats
          options: username=${{ github.repository_owner }}&show_icons=true&hide_title=true&include_all_commits=true&hide_border=true&count_private=true
          path: profile/stats.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate top languages card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: top-langs
          options: username=${{ github.repository_owner }}&hide_progress=false&hide=javascript,html,c,jupyter%20notebook,cuda&exclude_repo=CplusplusTutorial,ghostbasil,forked_seurat&langs_count=6&layout=compact
          path: profile/top-langs.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate pin card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: pin
          options: username=szcf-weiya&repo=ESL-CN
          path: profile/pin-szcf-weiya-ESL-CN.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate pin card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: pin
          options: username=szcf-weiya&repo=SinaSpider
          path: profile/pin-szcf-weiya-SinaSpider.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate pin card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: pin
          options: username=szcf-weiya&repo=MonteCarlo
          path: profile/pin-szcf-weiya-MonteCarlo.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate pin card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: pin
          options: username=szcf-weiya&repo=LaTeXTables.jl
          path: profile/pin-szcf-weiya-LaTeXTables-jl.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate pin card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: pin
          options: username=szcf-weiya&repo=techNotes
          path: profile/pin-szcf-weiya-techNotes.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate pin card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: pin
          options: username=szcf-weiya&repo=zju-thesis
          path: profile/pin-szcf-weiya-zju-thesis.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate pin card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: pin
          options: username=szcf-weiya&repo=benchmark.tree.regressions
          path: profile/pin-szcf-weiya-benchmark.tree.regressions.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate pin card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: pin
          options: username=szcf-weiya&repo=MonotoneSplines.jl
          path: profile/pin-szcf-weiya-MonotoneSplines.jl.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate pin card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: pin
          options: username=szcf-weiya&repo=MTWAS
          path: profile/pin-szcf-weiya-MTWAS.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate pin card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: pin
          options: username=szcf-weiya&repo=MonotoneDecomposition.jl
          path: profile/pin-szcf-weiya-MonotoneDecomposition.jl.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate pin card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: pin
          options: username=szcf-weiya&repo=TeXtemplates
          path: profile/pin-szcf-weiya-TeXtemplates.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate pin card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: pin
          options: username=szcf-weiya&repo=DegreesOfFreedom.jl
          path: profile/pin-szcf-weiya-DegreesOfFreedom.jl.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate pin card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: pin
          options: username=szcf-weiya&repo=earth.dof.patch
          path: profile/pin-szcf-weiya-earth.dof.patch.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate pin card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: pin
          options: username=szcf-weiya&repo=SplitClusterTest
          path: profile/pin-szcf-weiya-SplitClusterTest.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate pin card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: pin
          options: username=szcf-weiya&repo=SplitClusterTest.jl
          path: profile/pin-szcf-weiya-SplitClusterTest.jl.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate pin card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: pin
          options: username=szcf-weiya&repo=TriMatchMOT
          path: profile/pin-szcf-weiya-TriMatchMOT.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate pin card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: pin
          options: username=szcf-weiya&repo=fRLR
          path: profile/pin-szcf-weiya-fRLR.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate pin card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: pin
          options: username=szcf-weiya&repo=GSLwin
          path: profile/pin-szcf-weiya-GSLwin.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate pin card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: pin
          options: username=szcf-weiya&repo=Gibbs-Motif.jl
          path: profile/pin-szcf-weiya-Gibbs-Motif.jl.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate pin card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: pin
          options: username=szcf-weiya&repo=KmeansBenchmarks.jl
          path: profile/pin-szcf-weiya-KmeansBenchmarks.jl.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate pin card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: pin
          options: username=zxy0912&repo=TWASKnockoff
          path: profile/pin-zxy0912-TWASKnockoff.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit cards
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add profile/*.svg
          git commit -m "Update README cards" || exit 0
          git push
